apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-provider
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: s3-provider
  template:
    metadata:
      labels:
        name: s3-provider
    spec:
      containers:
        - name: s3fuse
          image: meain/s3-mounter
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: s3-config
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: s3-hdbfs
              mountPath: /var/s3hdb:shared
              readOnly: true
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: s3-hdbfs
          hostPath:
            path: /mnt/s3fs
            