apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kdb
  template:
    metadata:
      labels:
        app: kdb
    spec:
      containers:
        - name: s3fuse
          #image: meain/s3-mounter
          image: mshimizukx/kdb-hdb
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: s3-config
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: s3-hdbfs
              mountPath: /var/s3hdb
              readOnly: true
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: s3-hdbfs
          hostPath:
            path: /mnt/s3data
---
apiVersion: v1
kind: Service
metadata:
  name: hdb
spec:
  type: LoadBalancer
  selector:
    app: kdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
